apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 769911185966.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 769911185966.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 89e845c0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
